In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('InternetAds_norm_19.csv')  

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

att4  att5  att6  att7  att8  att9  att10  att11  att12  att13   ...     \
0   1.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0   ...      
1   1.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0   ...      
2   1.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0   ...      
3   1.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0   ...      
4   1.0   0.0   0.0   0.0   0.0   0.0    0.0    0.0    0.0    0.0   ...      

   att1550  att1551  att1552  att1553  att1554  att1555  att1556  att1557  \
0      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
1      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
2      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
3      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   
4      0.0      0.0      0.0      0.0      0.0      0.0      0.0      0.0   

   att1558  outlier  
0      0.0        1  
1      0.0        1  
2      0.0        1  
3      0.0        1  
4      0.0        1  

[5 rows x 1556 columns]

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/InternetAds.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,1555]
X = df[:,0:1555]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0 = time()
    # X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 20:17:13,352][cascade_classifier.fit_transform] X_groups_train.shape=[(2284, 1555)],y_train.shape=(2284,),X_groups_test.shape=[(980, 1555)],y_test.shape=(980,)
[ 2018-07-31 20:17:13,367][cascade_classifier.fit_transform] group_dims=[1555]
[ 2018-07-31 20:17:13,369][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 20:17:13,370][cascade_classifier.fit_transform] group_ends=[1555]
[ 2018-07-31 20:17:13,371][cascade_classifier.fit_transform] X_train.shape=(2284, 1555),X_test.shape=(980, 1555)
[ 2018-07-31 20:17:13,390][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(2284, 1555), X_cur_test.shape=(980, 1555)
[ 2018-07-31 20:17:14,598][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=94.32%
[ 2018-07-31 20:17:15,990][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=96.51%
[ 2018-07-31 20:17:17,206][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - e

[ 2018-07-31 20:18:02,396][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=97.11%
[ 2018-07-31 20:18:02,401][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=97.86%
[ 2018-07-31 20:18:02,456][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=96.94%
[ 2018-07-31 20:18:02,548][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=98.25%
[ 2018-07-31 20:18:02,589][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=96.94%
[ 2018-07-31 20:18:02,641][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=97.82%
[ 2018-07-31 20:18:02,697][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=97.81%
[ 2018-07-31 20:18:02,742][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=97.81%
[ 

[ 2018-07-31 20:18:38,340][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=97.37%
[ 2018-07-31 20:18:38,341][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=98.06%
[ 2018-07-31 20:18:39,398][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=97.82%
[ 2018-07-31 20:18:40,581][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=94.76%
[ 2018-07-31 20:18:41,637][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=97.38%
[ 2018-07-31 20:18:42,707][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=97.38%
[ 2018-07-31 20:18:43,813][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=98.25%
[ 2018-07-31 20:18:44,895][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=95.61%
[ 

[ 2018-07-31 20:19:12,631][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=98.16%
[ 2018-07-31 20:19:12,642][cascade_classifier.fit_transform] [layer=5] look_indexs=[0], X_cur_train.shape=(2284, 1561), X_cur_test.shape=(980, 1561)
[ 2018-07-31 20:19:13,539][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_0.predict)=98.25%
[ 2018-07-31 20:19:14,511][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_1.predict)=97.38%
[ 2018-07-31 20:19:15,499][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_2.predict)=97.82%
[ 2018-07-31 20:19:16,516][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_3.predict)=97.38%
[ 2018-07-31 20:19:17,448][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_4.predict)=97.37%
[ 2018-07-31 20:19:18,597][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_5.predi

In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 20:19:35,903][cascade_classifier.transform] X_groups_test.shape=[(980, 1555)]
[ 2018-07-31 20:19:35,907][cascade_classifier.transform] group_dims=[1555]
[ 2018-07-31 20:19:35,908][cascade_classifier.transform] X_test.shape=(980, 1555)
[ 2018-07-31 20:19:35,912][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(980, 1555)
[ 2018-07-31 20:19:40,695][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(980, 1561)
[ 2018-07-31 20:19:45,488][cascade_classifier.transform] [layer=2] look_indexs=[0], X_cur_test.shape=(980, 1561)


Test Accuracy of GCForest = 97.857143 %


In [9]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '156.999', ' seconds')
[[850  10]
 [ 11 109]]


             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99       860
        1.0       0.92      0.91      0.91       120

avg / total       0.98      0.98      0.98       980



# DecisionTreeClassifier

In [10]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 97.040816 %
(' Time ', '1.044', ' seconds')
[[843  17]
 [ 12 108]]


             precision    recall  f1-score   support

        0.0       0.99      0.98      0.98       860
        1.0       0.86      0.90      0.88       120

avg / total       0.97      0.97      0.97       980



# RandomForestClassifier

In [11]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 97.551020 %
(' Time ', '2.297', ' seconds')
[[848  12]
 [ 12 108]]


             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99       860
        1.0       0.90      0.90      0.90       120

avg / total       0.98      0.98      0.98       980



# ExtraTreesClassifier

In [12]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 97.448980 %
(' Time ', '4.025', ' seconds')
[[846  14]
 [ 11 109]]


             precision    recall  f1-score   support

        0.0       0.99      0.98      0.99       860
        1.0       0.89      0.91      0.90       120

avg / total       0.97      0.97      0.97       980



# AdaBoostClassifier

In [13]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 97.142857 %
(' Time ', '4.544', ' seconds')
[[849  11]
 [ 17 103]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.98       860
        1.0       0.90      0.86      0.88       120

avg / total       0.97      0.97      0.97       980



# Naive_bayes  GaussianNB

In [14]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 78.061224 %
(' Time ', '0.074', ' seconds')
[[651 209]
 [  6 114]]


             precision    recall  f1-score   support

        0.0       0.99      0.76      0.86       860
        1.0       0.35      0.95      0.51       120

avg / total       0.91      0.78      0.82       980



# Neural network 

In [15]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
2055/2055 [==============================] - 2s 903us/step - loss: 0.2444 - acc: 0.9163
Epoch 2/50
2055/2055 [==============================] - 1s 661us/step - loss: 0.0920 - acc: 0.9742
Epoch 3/50
2055/2055 [==============================] - 1s 684us/step - loss: 0.0602 - acc: 0.9830
Epoch 4/50
2055/2055 [==============================] - 1s 679us/step - loss: 0.0466 - acc: 0.9859
Epoch 5/50
2055/2055 [==============================] - 1s 661us/step - loss: 0.0400 - acc: 0.9869
Epoch 6/50
2055/2055 [==============================] - 1s 679us/step - loss: 0.0348 - acc: 0.9888
Epoch 7/50
2055/2055 [==============================] - 1s 573us/step - loss: 0.0338 - acc: 0.9898
Epoch 8/50
2055/2055 [==============================] - 1s 589us/step - loss: 0.0279 - acc: 0.9922
Epoch 9/50
2055/2055 [==============================] - 1s 658us/step - loss: 0.0279 - acc: 0.9912
Epoch 10/50
2055/2055 [==============================] - 1s 637us/step - loss: 0.0287 - acc: 0.9903
Epoch 11/

2055/2055 [==============================] - 1s 640us/step - loss: 0.0208 - acc: 0.9937
Epoch 33/50
2055/2055 [==============================] - 1s 626us/step - loss: 0.0190 - acc: 0.9932
Epoch 34/50
2055/2055 [==============================] - 1s 630us/step - loss: 0.0190 - acc: 0.9927
Epoch 35/50
2055/2055 [==============================] - 1s 586us/step - loss: 0.0193 - acc: 0.9937
Epoch 36/50
2055/2055 [==============================] - 1s 623us/step - loss: 0.0191 - acc: 0.9932
Epoch 37/50
2055/2055 [==============================] - 1s 654us/step - loss: 0.0186 - acc: 0.9932 1s - loss: 0.0
Epoch 38/50
2055/2055 [==============================] - 1s 611us/step - loss: 0.0190 - acc: 0.9942
Epoch 39/50
2055/2055 [==============================] - 1s 640us/step - loss: 0.0186 - acc: 0.9942
Epoch 40/50
2055/2055 [==============================] - 1s 628us/step - loss: 0.0188 - acc: 0.9932
Epoch 41/50
2055/2055 [==============================] - 1s 626us/step - loss: 0.0180 - acc: 0.99

Epoch 13/50
2055/2055 [==============================] - 1s 624us/step - loss: 0.0227 - acc: 0.9932
Epoch 14/50
2055/2055 [==============================] - 1s 641us/step - loss: 0.0252 - acc: 0.9932
Epoch 15/50
2055/2055 [==============================] - 1s 636us/step - loss: 0.0216 - acc: 0.9912
Epoch 16/50
2055/2055 [==============================] - 1s 632us/step - loss: 0.0217 - acc: 0.9937
Epoch 17/50
2055/2055 [==============================] - 1s 585us/step - loss: 0.0218 - acc: 0.9927
Epoch 18/50
2055/2055 [==============================] - 1s 580us/step - loss: 0.0202 - acc: 0.9927
Epoch 19/50
2055/2055 [==============================] - 1s 599us/step - loss: 0.0212 - acc: 0.9937
Epoch 20/50
2055/2055 [==============================] - 1s 652us/step - loss: 0.0209 - acc: 0.9942
Epoch 21/50
2055/2055 [==============================] - 1s 638us/step - loss: 0.0200 - acc: 0.9932
Epoch 22/50
2055/2055 [==============================] - 1s 630us/step - loss: 0.0208 - acc: 0.9922


2056/2056 [==============================] - 1s 684us/step - loss: 0.0180 - acc: 0.9937
Epoch 45/50
2056/2056 [==============================] - 1s 662us/step - loss: 0.0185 - acc: 0.9937
Epoch 46/50
2056/2056 [==============================] - 1s 658us/step - loss: 0.0182 - acc: 0.9942
Epoch 47/50
2056/2056 [==============================] - 1s 520us/step - loss: 0.0182 - acc: 0.9937
Epoch 48/50
2056/2056 [==============================] - 1s 641us/step - loss: 0.0177 - acc: 0.9942
Epoch 49/50
2056/2056 [==============================] - 1s 655us/step - loss: 0.0181 - acc: 0.9942A: 1s - loss: 0.0
Epoch 50/50
228/228 [==============================] - 0s 352us/step
Epoch 1/50
2056/2056 [==============================] - 2s 965us/step - loss: 0.2277 - acc: 0.9285
Epoch 2/50
2056/2056 [==============================] - 1s 663us/step - loss: 0.0854 - acc: 0.9762
Epoch 3/50
2056/2056 [==============================] - 1s 657us/step - loss: 0.0634 - acc: 0.9805
Epoch 4/50
2056/2056 [=======

2056/2056 [==============================] - 1s 574us/step - loss: 0.0180 - acc: 0.9932TA: 0s - loss: 0.0
Epoch 25/50
2056/2056 [==============================] - 1s 620us/step - loss: 0.0179 - acc: 0.9922
Epoch 26/50
2056/2056 [==============================] - 2s 797us/step - loss: 0.0177 - acc: 0.9942
Epoch 27/50
2056/2056 [==============================] - 2s 781us/step - loss: 0.0175 - acc: 0.9927 0s - loss: 0.0187
Epoch 28/50
2056/2056 [==============================] - 2s 792us/step - loss: 0.0179 - acc: 0.9937
Epoch 29/50
2056/2056 [==============================] - 1s 678us/step - loss: 0.0181 - acc: 0.9932
Epoch 30/50
2056/2056 [==============================] - 1s 587us/step - loss: 0.0179 - acc: 0.9937
Epoch 31/50
2056/2056 [==============================] - 1s 641us/step - loss: 0.0181 - acc: 0.9932
Epoch 32/50
2056/2056 [==============================] - 1s 621us/step - loss: 0.0180 - acc: 0.9937
Epoch 33/50
2056/2056 [==============================] - 1s 678us/step - los

2056/2056 [==============================] - 1s 625us/step - loss: 0.0484 - acc: 0.9849
Epoch 5/50
2056/2056 [==============================] - 1s 670us/step - loss: 0.0397 - acc: 0.9878
Epoch 6/50
2056/2056 [==============================] - 1s 660us/step - loss: 0.0395 - acc: 0.9883
Epoch 7/50
2056/2056 [==============================] - 1s 671us/step - loss: 0.0345 - acc: 0.9898
Epoch 8/50
2056/2056 [==============================] - 1s 655us/step - loss: 0.0384 - acc: 0.9888
Epoch 9/50
2056/2056 [==============================] - 1s 711us/step - loss: 0.0345 - acc: 0.9874
Epoch 10/50
2056/2056 [==============================] - 1s 729us/step - loss: 0.0284 - acc: 0.9917
Epoch 11/50
2056/2056 [==============================] - 1s 669us/step - loss: 0.0295 - acc: 0.9912
Epoch 12/50
2056/2056 [==============================] - 2s 755us/step - loss: 0.0275 - acc: 0.9917
Epoch 13/50
2056/2056 [==============================] - 2s 750us/step - loss: 0.0239 - acc: 0.9927
Epoch 14/50
2056/

2056/2056 [==============================] - 1s 675us/step - loss: 0.0155 - acc: 0.9951
Epoch 36/50
2056/2056 [==============================] - 1s 656us/step - loss: 0.0158 - acc: 0.9951
Epoch 37/50
2056/2056 [==============================] - 1s 643us/step - loss: 0.0156 - acc: 0.9942
Epoch 38/50
2056/2056 [==============================] - 1s 670us/step - loss: 0.0165 - acc: 0.9942
Epoch 39/50
2056/2056 [==============================] - 1s 571us/step - loss: 0.0155 - acc: 0.9951
Epoch 40/50
2056/2056 [==============================] - 1s 663us/step - loss: 0.0161 - acc: 0.9946
Epoch 41/50
2056/2056 [==============================] - 1s 609us/step - loss: 0.0160 - acc: 0.9951
Epoch 42/50
2056/2056 [==============================] - 1s 673us/step - loss: 0.0156 - acc: 0.9951
Epoch 43/50
2056/2056 [==============================] - 1s 674us/step - loss: 0.0154 - acc: 0.9946
Epoch 44/50
2056/2056 [==============================] - 1s 695us/step - loss: 0.0167 - acc: 0.9951
Epoch 45/50
