In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('SpamBase_withoutdupl_norm_40.csv')  

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

att1      att2      att3  att4   att5      att6      att7      att8  \
0  0.000000  0.044818  0.125490   0.0  0.032  0.000000  0.000000  0.000000   
1  0.046256  0.019608  0.098039   0.0  0.014  0.047619  0.028886  0.006301   
2  0.013216  0.000000  0.139216   0.0  0.123  0.032313  0.026135  0.010801   
3  0.000000  0.000000  0.000000   0.0  0.063  0.000000  0.042641  0.056706   
4  0.000000  0.000000  0.000000   0.0  0.063  0.000000  0.042641  0.056706   

       att9     att10   ...        att49     att50  att51     att52     att53  \
0  0.000000  0.000000   ...     0.000000  0.000000    0.0  0.023955  0.000000   
1  0.000000  0.051705   ...     0.000000  0.013536    0.0  0.011454  0.029985   
2  0.121673  0.013751   ...     0.002281  0.014664    0.0  0.008498  0.030651   
3  0.058935  0.034653   ...     0.000000  0.014048    0.0  0.004218  0.000000   
4  0.058935  0.034653   ...     0.000000  0.013843    0.0  0.004157  0.000000   

      att54     att55     att56     att57  outlier  
0  0.000000  0.002502  0.006007  0.017487        1  
1  0.002421  0.003735  0.010012  0.064836        1  
2  0.000504  0.008008  0.048458  0.142551        1  
3  0.000000  0.002303  0.003905  0.011995        1  
4  0.000000  0.002303  0.003905  0.011995        1  

[5 rows x 58 columns]

In [3]:
# df to values
df = df.values

In [4]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/SpamBase.json")   
gc = GCForest(config)

In [5]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,57]
X = df[:,0:57]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [6]:
# number of class
len(np.unique(y_train))

2

In [7]:
t0=time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 22:11:46,388][cascade_classifier.fit_transform] X_groups_train.shape=[(2944, 57)],y_train.shape=(2944,),X_groups_test.shape=[(1263, 57)],y_test.shape=(1263,)
[ 2018-07-31 22:11:46,391][cascade_classifier.fit_transform] group_dims=[57]
[ 2018-07-31 22:11:46,392][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 22:11:46,393][cascade_classifier.fit_transform] group_ends=[57]
[ 2018-07-31 22:11:46,394][cascade_classifier.fit_transform] X_train.shape=(2944, 57),X_test.shape=(1263, 57)
[ 2018-07-31 22:11:46,396][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(2944, 57), X_cur_test.shape=(1263, 57)
[ 2018-07-31 22:11:47,451][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=93.22%
[ 2018-07-31 22:11:48,695][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=94.24%
[ 2018-07-31 22:11:49,878][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 -

[ 2018-07-31 22:12:45,945][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=95.35%
[ 2018-07-31 22:12:45,946][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=94.54%
[ 2018-07-31 22:12:46,003][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=95.93%
[ 2018-07-31 22:12:46,066][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=93.56%
[ 2018-07-31 22:12:46,119][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=95.59%
[ 2018-07-31 22:12:46,170][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=95.25%
[ 2018-07-31 22:12:46,208][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=93.88%
[ 2018-07-31 22:12:46,245][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=94.56%
[ 

[ 2018-07-31 22:13:29,601][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=95.31%
[ 2018-07-31 22:13:29,602][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=94.70%
[ 2018-07-31 22:13:30,872][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=95.93%
[ 2018-07-31 22:13:32,398][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=95.59%
[ 2018-07-31 22:13:34,148][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=95.59%
[ 2018-07-31 22:13:35,796][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=95.93%
[ 2018-07-31 22:13:37,436][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=95.24%
[ 2018-07-31 22:13:39,181][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=95.58%
[ 

[ 2018-07-31 22:14:25,073][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=94.54%
[ 2018-07-31 22:14:25,076][cascade_classifier.fit_transform] [layer=5] look_indexs=[0], X_cur_train.shape=(2944, 63), X_cur_test.shape=(1263, 63)
[ 2018-07-31 22:14:26,591][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_0.predict)=94.58%
[ 2018-07-31 22:14:28,615][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_1.predict)=96.95%
[ 2018-07-31 22:14:31,027][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_2.predict)=94.92%
[ 2018-07-31 22:14:33,982][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_3.predict)=94.92%
[ 2018-07-31 22:14:36,750][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_4.predict)=95.58%
[ 2018-07-31 22:14:38,526][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_5.predict)

[ 2018-07-31 22:16:27,767][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_1.predict)=95.93%
[ 2018-07-31 22:16:27,826][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_2.predict)=96.95%
[ 2018-07-31 22:16:27,963][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_3.predict)=95.93%
[ 2018-07-31 22:16:28,051][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_4.predict)=94.22%
[ 2018-07-31 22:16:28,188][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_5.predict)=95.24%
[ 2018-07-31 22:16:28,321][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_6.predict)=94.56%
[ 2018-07-31 22:16:28,418][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_7.predict)=94.56%
[ 2018-07-31 22:16:28,533][kfold_wrapper.log_eval_metrics] Accuracy(layer_6 - estimator_2 - 10_folds.train_8.predict)=96.60%


[ 2018-07-31 22:18:18,101][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_1.predict)=94.58%
[ 2018-07-31 22:18:23,350][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_2.predict)=96.27%
[ 2018-07-31 22:18:27,556][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_3.predict)=93.90%
[ 2018-07-31 22:18:31,426][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_4.predict)=95.58%
[ 2018-07-31 22:18:34,663][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_5.predict)=97.96%
[ 2018-07-31 22:18:38,694][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_6.predict)=94.90%
[ 2018-07-31 22:18:41,396][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_7.predict)=96.94%
[ 2018-07-31 22:18:45,361][kfold_wrapper.log_eval_metrics] Accuracy(layer_8 - estimator_1 - 10_folds.train_8.predict)=95.58%


[ 2018-07-31 22:19:55,600][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_1.predict)=96.61%
[ 2018-07-31 22:19:57,939][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_2.predict)=95.93%
[ 2018-07-31 22:20:01,133][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_3.predict)=94.24%
[ 2018-07-31 22:20:03,188][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_4.predict)=96.94%
[ 2018-07-31 22:20:05,237][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_5.predict)=95.92%
[ 2018-07-31 22:20:07,347][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_6.predict)=95.92%
[ 2018-07-31 22:20:09,801][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_7.predict)=95.92%
[ 2018-07-31 22:20:12,736][kfold_wrapper.log_eval_metrics] Accuracy(layer_10 - estimator_0 - 10_folds.train_8.predict)

[ 2018-07-31 22:21:48,444][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_4.predict)=96.60%
[ 2018-07-31 22:21:48,595][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_5.predict)=94.90%
[ 2018-07-31 22:21:48,757][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_6.predict)=95.58%
[ 2018-07-31 22:21:48,963][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_7.predict)=95.58%
[ 2018-07-31 22:21:49,133][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_8.predict)=94.90%
[ 2018-07-31 22:21:49,338][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_9.predict)=96.26%
[ 2018-07-31 22:21:49,364][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.train_cv.predict)=95.58%
[ 2018-07-31 22:21:49,365][kfold_wrapper.log_eval_metrics] Accuracy(layer_11 - estimator_2 - 10_folds.test.predict)=9

[ 2018-07-31 22:23:26,638][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_4.predict)=95.58%
[ 2018-07-31 22:23:29,092][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_5.predict)=94.56%
[ 2018-07-31 22:23:31,850][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_6.predict)=95.24%
[ 2018-07-31 22:23:34,160][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_7.predict)=96.94%
[ 2018-07-31 22:23:36,847][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_8.predict)=93.88%
[ 2018-07-31 22:23:39,498][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_9.predict)=96.26%
[ 2018-07-31 22:23:39,894][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.train_cv.predict)=95.62%
[ 2018-07-31 22:23:39,896][kfold_wrapper.log_eval_metrics] Accuracy(layer_13 - estimator_1 - 10_folds.test.predict)=9

In [8]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 22:23:41,399][cascade_classifier.transform] X_groups_test.shape=[(1263, 57)]
[ 2018-07-31 22:23:41,407][cascade_classifier.transform] group_dims=[57]
[ 2018-07-31 22:23:41,409][cascade_classifier.transform] X_test.shape=(1263, 57)
[ 2018-07-31 22:23:41,410][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(1263, 57)
[ 2018-07-31 22:23:52,208][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(1263, 63)
[ 2018-07-31 22:24:01,639][cascade_classifier.transform] [layer=2] look_indexs=[0], X_cur_test.shape=(1263, 63)
[ 2018-07-31 22:24:13,446][cascade_classifier.transform] [layer=3] look_indexs=[0], X_cur_test.shape=(1263, 63)
[ 2018-07-31 22:24:25,002][cascade_classifier.transform] [layer=4] look_indexs=[0], X_cur_test.shape=(1263, 63)
[ 2018-07-31 22:24:34,744][cascade_classifier.transform] [layer=5] look_indexs=[0], X_cur_test.shape=(1263, 63)
[ 2018-07-31 22:24:41,989][cascade_classifier.transform] [layer=6] look_indexs=[0], 

Test Accuracy of GCForest = 94.615994 %


In [9]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '818.646', ' seconds')
[[701  37]
 [ 31 494]]


             precision    recall  f1-score   support

        0.0       0.96      0.95      0.95       738
        1.0       0.93      0.94      0.94       525

avg / total       0.95      0.95      0.95      1263



# Neural network 

In [10]:
t0 = time()
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
2649/2649 [==============================] - 4s 2ms/step - loss: 0.3502 - acc: 0.8784
Epoch 2/50
2649/2649 [==============================] - 2s 854us/step - loss: 0.2020 - acc: 0.9290
Epoch 3/50
2649/2649 [==============================] - 2s 877us/step - loss: 0.1893 - acc: 0.9298
Epoch 4/50
2649/2649 [==============================] - 2s 899us/step - loss: 0.1794 - acc: 0.9324
Epoch 5/50
2649/2649 [==============================] - 2s 921us/step - loss: 0.1623 - acc: 0.9404
Epoch 6/50
2649/2649 [==============================] - 2s 752us/step - loss: 0.1597 - acc: 0.9373
Epoch 7/50
2649/2649 [==============================] - 2s 786us/step - loss: 0.1466 - acc: 0.9449
Epoch 8/50
2649/2649 [==============================] - 2s 782us/step - loss: 0.1363 - acc: 0.9498 1s - l
Epoch 9/50
2649/2649 [==============================] - 2s 768us/step - loss: 0.1246 - acc: 0.9517
Epoch 10/50
2649/2649 [==============================] - 2s 689us/step - loss: 0.1176 - acc: 0.9558
Epoc

2649/2649 [==============================] - 2s 666us/step - loss: 0.0388 - acc: 0.9841
Epoch 33/50
2649/2649 [==============================] - 2s 773us/step - loss: 0.0323 - acc: 0.9894
Epoch 34/50
2649/2649 [==============================] - 2s 812us/step - loss: 0.0288 - acc: 0.9902
Epoch 35/50
2649/2649 [==============================] - 2s 794us/step - loss: 0.0303 - acc: 0.9868 1s -
Epoch 36/50
2649/2649 [==============================] - 2s 776us/step - loss: 0.0328 - acc: 0.9887
Epoch 37/50
2649/2649 [==============================] - 2s 747us/step - loss: 0.0247 - acc: 0.9909 0s - loss: 0.0246 - acc: 0.
Epoch 38/50
2649/2649 [==============================] - 2s 878us/step - loss: 0.0259 - acc: 0.9921
Epoch 39/50
2649/2649 [==============================] - 2s 754us/step - loss: 0.0303 - acc: 0.9894
Epoch 40/50
2649/2649 [==============================] - 2s 898us/step - loss: 0.0285 - acc: 0.9909
Epoch 41/50
2649/2649 [==============================] - 2s 837us/step - loss: 

2649/2649 [==============================] - 2s 614us/step - loss: 0.1179 - acc: 0.9570
Epoch 12/50
2649/2649 [==============================] - 2s 607us/step - loss: 0.1112 - acc: 0.9592
Epoch 13/50
2649/2649 [==============================] - 2s 708us/step - loss: 0.0995 - acc: 0.9641
Epoch 14/50
2649/2649 [==============================] - 2s 643us/step - loss: 0.0962 - acc: 0.9604
Epoch 15/50
2649/2649 [==============================] - 2s 661us/step - loss: 0.0919 - acc: 0.9656
Epoch 16/50
2649/2649 [==============================] - 1s 538us/step - loss: 0.0863 - acc: 0.9706
Epoch 17/50
2649/2649 [==============================] - 1s 512us/step - loss: 0.0755 - acc: 0.9728
Epoch 18/50
2649/2649 [==============================] - 1s 566us/step - loss: 0.0706 - acc: 0.9777
Epoch 19/50
2649/2649 [==============================] - 2s 567us/step - loss: 0.0851 - acc: 0.9713
Epoch 20/50
2649/2649 [==============================] - 2s 619us/step - loss: 0.0658 - acc: 0.9758
Epoch 21/50


2650/2650 [==============================] - 2s 619us/step - loss: 0.0245 - acc: 0.9925
Epoch 43/50
2650/2650 [==============================] - 1s 564us/step - loss: 0.0202 - acc: 0.9936
Epoch 44/50
2650/2650 [==============================] - 2s 598us/step - loss: 0.0231 - acc: 0.9928
Epoch 45/50
2650/2650 [==============================] - 1s 551us/step - loss: 0.0226 - acc: 0.9943
Epoch 46/50
2650/2650 [==============================] - 1s 566us/step - loss: 0.0223 - acc: 0.9932
Epoch 47/50
2650/2650 [==============================] - 1s 488us/step - loss: 0.0248 - acc: 0.9921
Epoch 48/50
2650/2650 [==============================] - 1s 463us/step - loss: 0.0331 - acc: 0.9883
Epoch 49/50
2650/2650 [==============================] - 1s 453us/step - loss: 0.0228 - acc: 0.9936
Epoch 50/50
294/294 [==============================] - 0s 517us/step
Epoch 1/50
2650/2650 [==============================] - 2s 688us/step - loss: 0.3361 - acc: 0.8528
Epoch 2/50
2650/2650 [======================

2650/2650 [==============================] - 1s 418us/step - loss: 0.0562 - acc: 0.9792
Epoch 23/50
2650/2650 [==============================] - 1s 424us/step - loss: 0.0596 - acc: 0.9758
Epoch 24/50
2650/2650 [==============================] - 1s 414us/step - loss: 0.0523 - acc: 0.9811
Epoch 25/50
2650/2650 [==============================] - 1s 403us/step - loss: 0.0505 - acc: 0.9819
Epoch 26/50
2650/2650 [==============================] - 1s 419us/step - loss: 0.0463 - acc: 0.9849
Epoch 27/50
2650/2650 [==============================] - 1s 414us/step - loss: 0.0458 - acc: 0.9823
Epoch 28/50
2650/2650 [==============================] - 1s 412us/step - loss: 0.0457 - acc: 0.9838
Epoch 29/50
2650/2650 [==============================] - 1s 406us/step - loss: 0.0440 - acc: 0.9849
Epoch 30/50
2650/2650 [==============================] - 1s 415us/step - loss: 0.0387 - acc: 0.9887
Epoch 31/50
2650/2650 [==============================] - 1s 408us/step - loss: 0.0393 - acc: 0.9879
Epoch 32/50


2650/2650 [==============================] - 1s 405us/step - loss: 0.2001 - acc: 0.9291
Epoch 3/50
2650/2650 [==============================] - 1s 406us/step - loss: 0.1856 - acc: 0.9309
Epoch 4/50
2650/2650 [==============================] - 1s 406us/step - loss: 0.1742 - acc: 0.9411
Epoch 5/50
2650/2650 [==============================] - 1s 415us/step - loss: 0.1654 - acc: 0.9404
Epoch 6/50
2650/2650 [==============================] - 1s 410us/step - loss: 0.1523 - acc: 0.9419
Epoch 7/50
2650/2650 [==============================] - 1s 408us/step - loss: 0.1495 - acc: 0.9434
Epoch 8/50
2650/2650 [==============================] - 1s 405us/step - loss: 0.1412 - acc: 0.9464
Epoch 9/50
2650/2650 [==============================] - 1s 407us/step - loss: 0.1317 - acc: 0.9464
Epoch 10/50
2650/2650 [==============================] - 1s 419us/step - loss: 0.1252 - acc: 0.9547
Epoch 11/50
2650/2650 [==============================] - 1s 423us/step - loss: 0.1127 - acc: 0.9589
Epoch 12/50
2650/26

2650/2650 [==============================] - 1s 404us/step - loss: 0.0424 - acc: 0.9842
Epoch 34/50
2650/2650 [==============================] - 1s 419us/step - loss: 0.0394 - acc: 0.9864
Epoch 35/50
2650/2650 [==============================] - 1s 405us/step - loss: 0.0273 - acc: 0.9917
Epoch 36/50
2650/2650 [==============================] - 1s 405us/step - loss: 0.0308 - acc: 0.9891
Epoch 37/50
2650/2650 [==============================] - 1s 429us/step - loss: 0.0269 - acc: 0.9898
Epoch 38/50
2650/2650 [==============================] - 1s 417us/step - loss: 0.0235 - acc: 0.9921
Epoch 39/50
2650/2650 [==============================] - 1s 420us/step - loss: 0.0250 - acc: 0.9917
Epoch 40/50
2650/2650 [==============================] - 1s 405us/step - loss: 0.0302 - acc: 0.9906
Epoch 41/50
2650/2650 [==============================] - 1s 404us/step - loss: 0.0362 - acc: 0.9864
Epoch 42/50
2650/2650 [==============================] - 1s 418us/step - loss: 0.0263 - acc: 0.9921
Epoch 43/50


# DecisionTreeClassifier

In [11]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 90.419636 %
(' Time ', '0.081', ' seconds')
[[672  66]
 [ 55 470]]


             precision    recall  f1-score   support

        0.0       0.92      0.91      0.92       738
        1.0       0.88      0.90      0.89       525

avg / total       0.90      0.90      0.90      1263



# RandomForestClassifier

In [12]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 94.457641 %
(' Time ', '1.119', ' seconds')
[[708  30]
 [ 40 485]]


             precision    recall  f1-score   support

        0.0       0.95      0.96      0.95       738
        1.0       0.94      0.92      0.93       525

avg / total       0.94      0.94      0.94      1263



# ExtraTreesClassifier

In [13]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of ExtraTreesClassifier = 95.011876 %
(' Time ', '1.118', ' seconds')
[[707  31]
 [ 32 493]]


             precision    recall  f1-score   support

        0.0       0.96      0.96      0.96       738
        1.0       0.94      0.94      0.94       525

avg / total       0.95      0.95      0.95      1263



# AdaBoostClassifier

In [14]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 94.378464 %
(' Time ', '1.07', ' seconds')
[[706  32]
 [ 39 486]]


             precision    recall  f1-score   support

        0.0       0.95      0.96      0.95       738
        1.0       0.94      0.93      0.93       525

avg / total       0.94      0.94      0.94      1263



# Naive_bayes  GaussianNB

In [15]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 81.631037 %
(' Time ', '0.008', ' seconds')
[[526 212]
 [ 20 505]]


             precision    recall  f1-score   support

        0.0       0.96      0.71      0.82       738
        1.0       0.70      0.96      0.81       525

avg / total       0.86      0.82      0.82      1263

