In [1]:
#Imports 
import numpy as np
import pandas as pd
from math import sqrt 
from pprint import pprint
from numpy import array
from time import time

In [2]:
# load data
df=pd.read_csv('Cardiotocography_02_v10.csv')  

del df['id']
del df['Unnamed: 0']
df['outlier'] = df.outlier.apply(lambda label: 1 if label == "'yes'" else 0)

df.head()

LB   AC   FM   UC  ASTV  MSTV  ALTV  MLTV   DL   DS   ...       Min  \
0  146.0  0.0  0.0  5.0  65.0   0.4  33.0   7.4  0.0  0.0   ...     134.0   
1  128.0  0.0  0.0  2.0  86.0   0.3  79.0   2.9  0.0  0.0   ...     114.0   
2  149.0  0.0  0.0  5.0  61.0   0.4  34.0   5.6  0.0  0.0   ...     148.0   
3  122.0  0.0  0.0  0.0  83.0   0.5   6.0  15.6  0.0  0.0   ...      62.0   
4  134.0  0.0  4.0  0.0  79.0   0.2  42.0   5.5  0.0  0.0   ...     128.0   

     Max  Nmax  Nzeros   Mode   Mean  Median  Variance  Tendency  outlier  
0  164.0   1.0     0.0  150.0  149.0   151.0       1.0       0.0        1  
1  130.0   0.0     0.0  128.0  126.0   129.0       0.0       1.0        1  
2  160.0   1.0     0.0  154.0  153.0   155.0       0.0       0.0        1  
3  130.0   0.0     0.0  122.0  122.0   123.0       3.0       1.0        1  
4  145.0   2.0     0.0  135.0  135.0   136.0       1.0       0.0        1  

[5 rows x 22 columns]

In [3]:
# first 5 
df.shape

(1688, 22)

In [4]:
# df to values
df = df.values

In [5]:
# GC Forest
import argparse
import sys
import pickle
from sklearn.metrics import accuracy_score
sys.path.insert(0, "lib")
from gcforest.gcforest import GCForest
from gcforest.gcforest import GCForest
from gcforest.utils.config_utils import load_json
config = load_json("./examples/Cardiotocography.json")   
gc = GCForest(config)

In [6]:
# train test 
from sklearn.cross_validation import train_test_split
y = df[:,21]
X = df[:,0:21]

X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.3, random_state=0)

/home/ubuntu/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [7]:
# number of class
len(np.unique(y_train))

2

In [8]:
t0 = time()
# X_enc is the concatenated predict_proba result of each estimators of the last layer of the GCForest model
    # X_enc.shape =
    #   (n_datas, n_estimators * n_classes): If cascade is provided
    #   (n_datas, n_estimators * n_classes, dimX, dimY): If only finegrained part is provided
    # You can also pass X_test, y_test to fit_transform method, then the accracy on test data will be logged when training.
X_train_enc, X_test_enc = gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test)
    # WARNING: if you set gc.set_keep_model_in_mem(True), you would have to use
    # gc.fit_transform(X_train, y_train, X_test=X_test, y_test=y_test) to evaluate your model. 

[ 2018-07-31 16:52:05,225][cascade_classifier.fit_transform] X_groups_train.shape=[(1181, 21)],y_train.shape=(1181,),X_groups_test.shape=[(507, 21)],y_test.shape=(507,)
[ 2018-07-31 16:52:05,227][cascade_classifier.fit_transform] group_dims=[21]
[ 2018-07-31 16:52:05,228][cascade_classifier.fit_transform] group_starts=[0]
[ 2018-07-31 16:52:05,234][cascade_classifier.fit_transform] group_ends=[21]
[ 2018-07-31 16:52:05,236][cascade_classifier.fit_transform] X_train.shape=(1181, 21),X_test.shape=(507, 21)
[ 2018-07-31 16:52:05,237][cascade_classifier.fit_transform] [layer=0] look_indexs=[0], X_cur_train.shape=(1181, 21), X_cur_test.shape=(507, 21)
[ 2018-07-31 16:52:05,959][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_0.predict)=98.32%
[ 2018-07-31 16:52:07,114][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_folds.train_1.predict)=98.31%
[ 2018-07-31 16:52:07,921][kfold_wrapper.log_eval_metrics] Accuracy(layer_0 - estimator_0 - 10_

[ 2018-07-31 16:52:37,247][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.train_cv.predict)=98.81%
[ 2018-07-31 16:52:37,248][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_1 - 10_folds.test.predict)=97.63%
[ 2018-07-31 16:52:37,281][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_0.predict)=98.32%
[ 2018-07-31 16:52:37,311][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_1.predict)=98.31%
[ 2018-07-31 16:52:37,339][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_2.predict)=98.31%
[ 2018-07-31 16:52:37,370][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_3.predict)=98.31%
[ 2018-07-31 16:52:37,405][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_4.predict)=98.31%
[ 2018-07-31 16:52:37,432][kfold_wrapper.log_eval_metrics] Accuracy(layer_1 - estimator_2 - 10_folds.train_5.predict)=98.31%
[ 

[ 2018-07-31 16:53:00,067][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.train_cv.predict)=98.56%
[ 2018-07-31 16:53:00,068][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_0 - 10_folds.test.predict)=97.83%
[ 2018-07-31 16:53:00,562][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_0.predict)=99.16%
[ 2018-07-31 16:53:01,278][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_1.predict)=98.31%
[ 2018-07-31 16:53:01,998][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_2.predict)=98.31%
[ 2018-07-31 16:53:02,847][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_3.predict)=99.15%
[ 2018-07-31 16:53:03,570][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_4.predict)=98.31%
[ 2018-07-31 16:53:04,285][kfold_wrapper.log_eval_metrics] Accuracy(layer_3 - estimator_1 - 10_folds.train_5.predict)=99.15%
[ 

[ 2018-07-31 16:53:22,478][cascade_classifier.calc_accuracy] Accuracy(layer_4 - test.classifier_average)=97.63%
[ 2018-07-31 16:53:22,479][cascade_classifier.fit_transform] [layer=5] look_indexs=[0], X_cur_train.shape=(1181, 27), X_cur_test.shape=(507, 27)
[ 2018-07-31 16:53:23,124][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_0.predict)=98.32%
[ 2018-07-31 16:53:23,911][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_1.predict)=99.15%
[ 2018-07-31 16:53:24,532][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_2.predict)=99.15%
[ 2018-07-31 16:53:25,155][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_3.predict)=98.31%
[ 2018-07-31 16:53:25,893][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_4.predict)=98.31%
[ 2018-07-31 16:53:26,636][kfold_wrapper.log_eval_metrics] Accuracy(layer_5 - estimator_0 - 10_folds.train_5.predict)=

In [9]:
# predict
y_pred = gc.predict(X_test)
acc = accuracy_score(y_test, y_pred)
print("Test Accuracy of GCForest = {:.6f} %".format(acc * 100))

[ 2018-07-31 16:53:37,184][cascade_classifier.transform] X_groups_test.shape=[(507, 21)]
[ 2018-07-31 16:53:37,186][cascade_classifier.transform] group_dims=[21]
[ 2018-07-31 16:53:37,186][cascade_classifier.transform] X_test.shape=(507, 21)
[ 2018-07-31 16:53:37,188][cascade_classifier.transform] [layer=0] look_indexs=[0], X_cur_test.shape=(507, 21)
[ 2018-07-31 16:53:41,036][cascade_classifier.transform] [layer=1] look_indexs=[0], X_cur_test.shape=(507, 27)
[ 2018-07-31 16:53:43,704][cascade_classifier.transform] [layer=2] look_indexs=[0], X_cur_test.shape=(507, 27)


Test Accuracy of GCForest = 97.830375 %


In [10]:
tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

(' Time ', '101.735', ' seconds')
[[493   1]
 [ 10   3]]


             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99       494
        1.0       0.75      0.23      0.35        13

avg / total       0.97      0.98      0.97       507



# DecisionTreeClassifier

In [11]:
t0 = time()
from sklearn.tree import DecisionTreeClassifier
clf = DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of DecisionTreeClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of DecisionTreeClassifier = 97.633136 %
(' Time ', '0.009', ' seconds')
[[491   3]
 [  9   4]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.99       494
        1.0       0.57      0.31      0.40        13

avg / total       0.97      0.98      0.97       507



# RandomForestClassifier

In [12]:
t0 = time()
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of RandomForestClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of RandomForestClassifier = 97.435897 %
(' Time ', '0.402', ' seconds')
[[493   1]
 [ 12   1]]


             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99       494
        1.0       0.50      0.08      0.13        13

avg / total       0.96      0.97      0.97       507



# ExtraTreesClassifier

In [13]:
t0 = time()
from sklearn.ensemble import ExtraTreesClassifier
clf = ExtraTreesClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of ExtraTreesClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))


Test Accuracy of ExtraTreesClassifier = 97.633136 %
(' Time ', '0.35', ' seconds')
[[494   0]
 [ 12   1]]


             precision    recall  f1-score   support

        0.0       0.98      1.00      0.99       494
        1.0       1.00      0.08      0.14        13

avg / total       0.98      0.98      0.97       507



# AdaBoostClassifier

In [14]:
t0 = time()
from sklearn.ensemble import AdaBoostClassifier
clf = AdaBoostClassifier(n_estimators=100)
clf = clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of AdaBoostClassifier = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of AdaBoostClassifier = 97.238659 %
(' Time ', '0.322', ' seconds')
[[491   3]
 [ 11   2]]


             precision    recall  f1-score   support

        0.0       0.98      0.99      0.99       494
        1.0       0.40      0.15      0.22        13

avg / total       0.96      0.97      0.97       507



# Naive_bayes  GaussianNB

In [15]:
t0 = time()
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb = gnb.fit(X_train, y_train)

y_pred= gnb.predict(X_test)
acc = accuracy_score(y_test, y_pred)

print("Test Accuracy of GaussianNB = {:.6f} %".format(acc * 100))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Test Accuracy of GaussianNB = 93.293886 %
(' Time ', '0.003', ' seconds')
[[467  27]
 [  7   6]]


             precision    recall  f1-score   support

        0.0       0.99      0.95      0.96       494
        1.0       0.18      0.46      0.26        13

avg / total       0.96      0.93      0.95       507



# Neural network 

In [16]:
# estimators 
# Evaluating the ANN
t0 = time()
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import cross_val_score
from keras.models import Sequential # initialize neural network library
from keras.layers import Dense # build our layers library
def build_classifier():
    classifier = Sequential() # initialize neural network
    classifier.add(Dense(units = 1024, kernel_initializer = 'uniform', activation = 'relu', input_dim = X_train.shape[1]))
    classifier.add(Dense(units = 512, kernel_initializer = 'uniform', activation = 'relu'))
    classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))
    classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
    return classifier
classifier = KerasClassifier(build_fn = build_classifier, epochs = 50)
accuracies = cross_val_score(estimator = classifier, X = X_train, y = y_train, cv = 10)
mean = accuracies.mean()
variance = accuracies.std()
print("Accuracy mean: "+ str(mean))
print("Accuracy variance: "+ str(variance))

tt = time() - t0     
print (" Time ",format(round(tt,3))," seconds")
# Matrix de confusion
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print('\n')
print(classification_report(y_test,y_pred))

Using TensorFlow backend.


Epoch 1/50
1062/1062 [==============================] - 0s 461us/step - loss: 0.2524 - acc: 0.9831
Epoch 2/50
1062/1062 [==============================] - 0s 179us/step - loss: 0.2732 - acc: 0.9831
Epoch 3/50
1062/1062 [==============================] - 0s 187us/step - loss: 0.2732 - acc: 0.9831
Epoch 4/50
1062/1062 [==============================] - 0s 192us/step - loss: 0.2732 - acc: 0.9831
Epoch 5/50
1062/1062 [==============================] - 0s 192us/step - loss: 0.2732 - acc: 0.9831
Epoch 6/50
1062/1062 [==============================] - 0s 181us/step - loss: 0.2732 - acc: 0.9831
Epoch 7/50
1062/1062 [==============================] - 0s 182us/step - loss: 0.2732 - acc: 0.9831
Epoch 8/50
1062/1062 [==============================] - 0s 188us/step - loss: 0.2732 - acc: 0.9831
Epoch 9/50
1062/1062 [==============================] - 0s 185us/step - loss: 0.2732 - acc: 0.9831
Epoch 10/50
1062/1062 [==============================] - 0s 186us/step - loss: 0.2732 - acc: 0.9831
Epoch 11/

1063/1063 [==============================] - 0s 182us/step - loss: 0.2729 - acc: 0.9831
Epoch 33/50
1063/1063 [==============================] - 0s 171us/step - loss: 0.2729 - acc: 0.9831
Epoch 34/50
1063/1063 [==============================] - 0s 172us/step - loss: 0.2729 - acc: 0.9831
Epoch 35/50
1063/1063 [==============================] - 0s 165us/step - loss: 0.2729 - acc: 0.9831
Epoch 36/50
1063/1063 [==============================] - 0s 174us/step - loss: 0.2729 - acc: 0.9831
Epoch 37/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2729 - acc: 0.9831
Epoch 38/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2729 - acc: 0.9831
Epoch 39/50
1063/1063 [==============================] - 0s 170us/step - loss: 0.2729 - acc: 0.9831
Epoch 40/50
1063/1063 [==============================] - 0s 178us/step - loss: 0.2729 - acc: 0.9831
Epoch 41/50
1063/1063 [==============================] - 0s 178us/step - loss: 0.2729 - acc: 0.9831
Epoch 42/50


1063/1063 [==============================] - 0s 174us/step - loss: 0.2729 - acc: 0.9831
Epoch 13/50
1063/1063 [==============================] - 0s 170us/step - loss: 0.2729 - acc: 0.9831
Epoch 14/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2729 - acc: 0.9831
Epoch 15/50
1063/1063 [==============================] - 0s 172us/step - loss: 0.2729 - acc: 0.9831
Epoch 16/50
1063/1063 [==============================] - 0s 181us/step - loss: 0.2729 - acc: 0.9831
Epoch 17/50
1063/1063 [==============================] - 0s 169us/step - loss: 0.2729 - acc: 0.9831
Epoch 18/50
1063/1063 [==============================] - 0s 175us/step - loss: 0.2729 - acc: 0.9831
Epoch 19/50
1063/1063 [==============================] - 0s 173us/step - loss: 0.2729 - acc: 0.9831
Epoch 20/50
1063/1063 [==============================] - 0s 174us/step - loss: 0.2729 - acc: 0.9831
Epoch 21/50
1063/1063 [==============================] - 0s 173us/step - loss: 0.2729 - acc: 0.9831
Epoch 22/50


1063/1063 [==============================] - 0s 177us/step - loss: 0.2729 - acc: 0.9831
Epoch 44/50
1063/1063 [==============================] - 0s 174us/step - loss: 0.2729 - acc: 0.9831
Epoch 45/50
1063/1063 [==============================] - 0s 170us/step - loss: 0.2729 - acc: 0.9831
Epoch 46/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2729 - acc: 0.9831
Epoch 47/50
1063/1063 [==============================] - 0s 174us/step - loss: 0.2729 - acc: 0.9831
Epoch 48/50
1063/1063 [==============================] - 0s 176us/step - loss: 0.2729 - acc: 0.9831
Epoch 49/50
1063/1063 [==============================] - 0s 172us/step - loss: 0.2729 - acc: 0.9831
Epoch 50/50
118/118 [==============================] - 0s 543us/step
Epoch 1/50
1063/1063 [==============================] - 1s 761us/step - loss: 0.2743 - acc: 0.9831
Epoch 2/50
1063/1063 [==============================] - 0s 175us/step - loss: 0.2729 - acc: 0.9831
Epoch 3/50
1063/1063 [=======================

1063/1063 [==============================] - 0s 180us/step - loss: 0.2578 - acc: 0.9840
Epoch 25/50
1063/1063 [==============================] - 0s 175us/step - loss: 0.2578 - acc: 0.9840
Epoch 26/50
1063/1063 [==============================] - 0s 176us/step - loss: 0.2578 - acc: 0.9840
Epoch 27/50
1063/1063 [==============================] - 0s 186us/step - loss: 0.2578 - acc: 0.9840
Epoch 28/50
1063/1063 [==============================] - 0s 200us/step - loss: 0.2578 - acc: 0.9840
Epoch 29/50
1063/1063 [==============================] - 0s 192us/step - loss: 0.2578 - acc: 0.9840
Epoch 30/50
1063/1063 [==============================] - 0s 179us/step - loss: 0.2578 - acc: 0.9840
Epoch 31/50
1063/1063 [==============================] - 0s 199us/step - loss: 0.2578 - acc: 0.9840
Epoch 32/50
1063/1063 [==============================] - 0s 243us/step - loss: 0.2578 - acc: 0.9840
Epoch 33/50
1063/1063 [==============================] - 0s 223us/step - loss: 0.2578 - acc: 0.9840
Epoch 34/50


1063/1063 [==============================] - 0s 296us/step - loss: 0.2274 - acc: 0.9859
Epoch 5/50
1063/1063 [==============================] - 0s 328us/step - loss: 0.2274 - acc: 0.9859
Epoch 6/50
1063/1063 [==============================] - 0s 308us/step - loss: 0.2274 - acc: 0.9859
Epoch 7/50
1063/1063 [==============================] - 0s 361us/step - loss: 0.2274 - acc: 0.9859
Epoch 8/50
1063/1063 [==============================] - 0s 363us/step - loss: 0.2274 - acc: 0.9859
Epoch 9/50
1063/1063 [==============================] - 0s 257us/step - loss: 0.2274 - acc: 0.9859
Epoch 10/50
1063/1063 [==============================] - 0s 288us/step - loss: 0.2274 - acc: 0.9859
Epoch 11/50
1063/1063 [==============================] - 0s 275us/step - loss: 0.2274 - acc: 0.9859
Epoch 12/50
1063/1063 [==============================] - 0s 328us/step - loss: 0.2274 - acc: 0.9859
Epoch 13/50
1063/1063 [==============================] - 0s 319us/step - loss: 0.2274 - acc: 0.9859
Epoch 14/50
1063/

1063/1063 [==============================] - 0s 191us/step - loss: 0.2881 - acc: 0.9821
Epoch 36/50
1063/1063 [==============================] - 0s 186us/step - loss: 0.2881 - acc: 0.9821
Epoch 37/50
1063/1063 [==============================] - 0s 174us/step - loss: 0.2881 - acc: 0.9821
Epoch 38/50
1063/1063 [==============================] - 0s 181us/step - loss: 0.2881 - acc: 0.9821
Epoch 39/50
1063/1063 [==============================] - 0s 181us/step - loss: 0.2881 - acc: 0.9821
Epoch 40/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2881 - acc: 0.9821
Epoch 41/50
1063/1063 [==============================] - 0s 181us/step - loss: 0.2881 - acc: 0.9821
Epoch 42/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2881 - acc: 0.9821
Epoch 43/50
1063/1063 [==============================] - 0s 178us/step - loss: 0.2881 - acc: 0.9821
Epoch 44/50
1063/1063 [==============================] - 0s 177us/step - loss: 0.2881 - acc: 0.9821
Epoch 45/50
